README.md

It seem like a great idea to highlight only the "app" name and leave out the description.

Highlight only app name

---

README.md

* Add Example Apps category
* Add preact-hn to examples list
cc @kristoferbaxter ?

Add preact-hn

---

README.md

Add Preact Material Components

---

README.md

Added components from the preact docs?? Thanks to @lukeed

Add more components

---

CONTRIBUTING.md

- Can use emojis before descriptions
- Articles should remain as is it. Added it for better clarification.

Amend CONTRIBUTING.md

---

contributing.md
readme.md

Icons seem distracting. Took them out

Add Article, Remove icons

---

readme.md

- Create Libraries Category
- Add FPreact Library

Create Category & Add Functional Preact

---

readme.md

**Introducing Redux Zero**
https://medium.com/@matheusml/introducing-redux-zero-bea42214c7ee
> Redux Zero is a lightweight state container based on Redux with a single store and no reducers, 100% written in TypeScript. Less than 1kb (gzip).  Made for (p)react ⚛️ 
> A big shoutout to Jason Miller, because Redux Zero was heavily inspired by his [gist](https://gist.github.com/developit/55c48d294abab13a146eac236bae3219).
> Also, a big shoutout to Kent C. Dodds, because this was inspired by his [Introducing Downshift](https://blog.kentcdodds.com/introducing-downshift-for-react-b1de3fca0817) post.
> And of course, a big shoutout to Dan Abramov because without Redux, Redux Zero wouldn’t exist.

Add "Redux Zero"

---

readme.md

Add Preact Fluid

---

readme.md

https://github.com/therealparmesh/preact-boilerplate

Add Preact Boilerplate (using Parcel)

---

readme.md

https://github.com/Sobesednik/preact-animate-on-change

Add preact-animate-on-change

---

readme.md

**Repo URL:** https://github.com/mobiushorizons/mu-forms
**Twitter Username:** MobiusHorizons
**Description:**

Add MU Forms

---

readme.md

Reverts ooade/awesome-preact#31

Revert "Add Preact Testing Library"

---

readme.md

**Repo URL:** https://github.com/antoaravinth/preact-testing-library
**Twitter Username:** antoaravinth
**Description:**

Add Preact Testing Library

---

readme.md

[![banner](https://user-images.githubusercontent.com/20046/40874682-a7b9d09c-6672-11e8-99c7-1c6ae190d6e6.png)](https://proppyjs.com)
* Website: https://proppyjs.com
* Docs: https://proppyjs.com/docs/introduction
* API: https://proppyjs.com/docs/api
* GitHub: https://github.com/fahad19/proppy

Add ProppyJS

---

readme.md

**Repo URL:** https://github.com/haensl/preact-component-console
**Twitter Username:** [@h_p_d](https://twitter.com/h_p_d)
**Description:** Console emulator preact component. Simulates typing via dynamic delays.

Add preact-component-console.

---

readme.md

**Repo URL:** 
https://github.com/code-and-comment/code-and-comment
**Twitter Username:** 
[38elements](https://twitter.com/38elements)
**Description:** 
The application to add the comments to a file in Github.
This is built with Preact, unistore and preact-router.

Add Code and Comment to Example Apps section

---

readme.md

**Twitter Username:** BartWaardenburg
**Description:** It's now possible to create a storybook environment specifically for Preact components (https://www.npmjs.com/package/@storybook/preact).

Add @storybook/preact to toolkits

---

readme.md

**Repo URL:** https://github.com/Autodesk/clearx
**Twitter Username:** @UndefinedN
**Description:** Fast & Effortless global state management for React, Preact and Inferno with zero learning curve.

Add ClearX state management library

---

readme.md

**Twitter Username:**  PradeepBaradur
**Description:**  Updated the link.

Update link for React App Rewire Preact

---

readme.md

In the preact repository we are removing a lot of content from our README, I'm adding it here for visibility (+ linking to here) https://github.com/preactjs/preact/pull/2232

Add example projects

---

readme.md

**Repo URL:** https://github.com/SafdarJamal/vanilla-preact
**Twitter Username:** _safdarjamal
**Description:** A barebones starter kit for building preact applications without build or tooling.

Add vanilla-preact-app to the example apps

---

readme.md

**Repo URL:** https://github.com/code2k/ghfresh
**Twitter Username:** @code2klabs
**Description:** SPA for monitoring GitHub releases. Build using Preact, Typescript, create-react-app, Material-UI, Redux Toolkit.

Add GHFresh example app

---

readme.md

**Repo URL:**
https://github.com/JoviDeCroock/hooked-head
**Twitter Username:**
https://twitter.com/JoviDeC
**Description:**
A library that uses hooks to populate the `<head>`, this uses a small reconciler to ensure effects are executed in the right order.

add hooked-head

---

readme.md

**Repo URL:** https://github.com/kolodziejczakM/passwords-fountain
**Twitter Username:** [@kolodziejczakMn](https://twitter.com/kolodziejczakMn)
**Description:** Modern & performant password manager interface which works everywhere

Add Passwords Fountain to Example Apps section

---

readme.md

**Repo URL:** https://github.com/matteobruni/tsparticles#preact
**Twitter Username:** HollowMatt_ITA
**Description:** Lightweight Preact component to easily add cool particles animations to websites

Added Preact Particles

---

readme.md

**Repo URL:** https://github.com/TimDaub/preact-touchable-dock
**Twitter Username:** don't have one
**Description:** A simple DnD and touch-enabled Dock component for preact. Check repo for more infos and demo

Add Preact Dock

---

readme.md

**Repo URL:** https://github.com/webyom/pant
**Twitter Username:** don't have one
**Description:** Mobile UI Components built on Preact *([docs and demos](https://webyom.github.io/pant))*. Ported from awesome Vue components of [Vant](https://github.com/youzan/vant).

Add Pant to Components section

---

readme.md

**Repo URL:** https://github.com/vitejs/vite
**Twitter Username:** `@concreteniche`
**Description:** Fast dev server via on-demand ES modules for Preact, React, or Vue; uses Rollup for production builds.

Add link to Vite

---

readme.md

**Repo URL:** https://github.com/PuruVJ/macos-web
**Twitter Username:** [@puruvjdev](https://twitter.com/puruvjdev)

Add macOS Web to list

---

readme.md

This is not mine but I use it and it's great!
Repo: https://github.com/developit/unistore

Add Unistore to libs section

---

readme.md

**Repo URL:** 
**Twitter Username:** 
**Description:** https://cinemate.me - a website built using Preact.

Add Cinemate website

---

readme.md

**Repo URL:** https://github.com/fakundo/preact-transitioning
**Twitter Username:** -
**Description:** Exposes Preact components for easily implementing basic CSS animations and transitions.

Add preact-transitioning

---

readme.md

**Repo URL:** https://github.com/puruvj/macos-preact
**Twitter Username:** puruvjdev

Update macOS Web

---

readme.md

**Repo URL:** https://github.com/kolodziejczakM/preact-modern-startupper
**Twitter Username:** [@kolodziejczakMn](https://twitter.com/kolodziejczakMn)
**Description:** This is minimalistic boilerplate repository which goal is to boost productivity of small / middle size real world web projects and make new apps highly optimised.
Current bundle size (gzipped) is 19.4 KB.
You: Why should I care❓❓
easy to use boilerplate generators for components and modules
ready to use storybook support
side effects handling - through unistore - additional middlewares are not needed
store compatible with Redux DevTools
localisation support - you can easily start developing multiple-language app
pre-rendering support - you can render static HTML webpages out of app routes
battle-tested project structure - …

Add Preact Modern Startupper to boilerplate section

---

.github/PULL_REQUEST_TEMPLATE.md
contributing.md

Couple things:
- Stop asking for Twitter usernames since we haven't really been able to maintain the bot that gives shoutouts. Also, not everyone is on Twitter 😄
- There's also no need to ask for the link to the project here since it's already specified in the readme while sending the PR. It was also previously used by the bot.
- The proposed checklist is more like a `TLDR;` of our contributing guideline.

Update the PR template

---

readme.md

Preact-Webext:- https://github.com/PiyushSuthar/preact-webext
Windows 11 Web:- https://github.com/PiyushSuthar/Windows-11-Web
**Twitter Username**: Piyushsthr

Add Preact-Webext and Windows 11 Web

---

readme.md

Add Teaful as library

---

readme.md

Add Yoctopuce Electron Preact boilerplate project

---

readme.md

Add Preact Nominal Allocator component link

---

readme.md

I've created a starter project for building lightweight desktop applications with Preact and neutralino.js framework, and I'd like to share it with other people.

Neutralino boilerplate

---

readme.md

idea keeper 2 - https://github.com/MiftikCZ/idea-keeper-2 made in Preact.ts and Vite.
a highly extensible idea keeping app

Added example app

---

readme.md

Add [Tailored Components](https://github.com/nesterow/tailored) - Components and hooks for Preact 
Add [Simple Deno Starter](https://github.com/nesterow/minizavr) -  Tiny starter template for Deno

Add Tailored Components and Simple Deno Starter

---

readme.md

I would like to add the library/set of components for creating forms in Preact. It's a pretty mature project that we use in our company, and someone might find it useful. I know there are already MU Forms and Modular Forms on the list, so be free to decline this PR.
Docs: https://shelacek.bitbucket.io/formica
Repo: https://bitbucket.org/shelacek/formica
NPM: https://www.npmjs.com/package/@shelacek/formica

Add Formica

---

readme.md

Plotery is a small but extensible charting library for Preact.
Docs: https://shelacek.bitbucket.io/plotery
Repo: https://bitbucket.org/shelacek/plotery
NPM: https://www.npmjs.com/package/@shelacek/plotery

Add Plotery

---

readme.md

I made a tiny trello clone PWA using Preact.

Add Trellith

---

readme.md

[Gladys Assistant](https://gladysassistant.com/) - A privacy-first, open-source home assistant made with Preact.

Added example app : Gladys Assistant
